### ISSUE TITLE
Missing cc logo when logoff

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#11]
To fix

**Comment by blackcrack** [comment]
i have at 27.10 up to 15.11 leave of absence, i hope i can me involving into the code :)
by the way, the ccpage for the logo, there:
http://creativecommons.org/licenses/
and
https://creativecommons.org/about/downloads/
(the logo's) (maybe i build an better cc logo for us :)
at moment, 11:00am at work and 8:00pm driving home..(9:00 at home and jup in my' bed..)
best regards
Blacky
