### ISSUE TITLE
Sessionlocation changing

### ISSUE THREAD

**Issue by blackcrack** [PHP-Outburst/myUPB#12]
on 

http://www.polarhome.com:793/~blackcra/forum/
we should let create an ./sessions folder like database and upload 
and use this as $psfolder (php-sessions-folder)

for have at all in the webspace and don't need put into the system, to be only in the web space
and don't touch the System-security. Very well for Providers and Secure Web-servers with more as one web space client .

[quote]
Warning: session_start(): open(/var/lib/php/session/sess_8l1c9tr5pht6m1s6hs4albegk3, O_RDWR) failed: Permission denied (13) in /home/b/blackcra/public_html/forum/includes/upb.initialize.php on line 77
[/quote]

best regards
Blacky

**Comment by halamix2** [comment]
Connected with #40, I overlooked all old issues when creating new ones ._.
