### ISSUE TITLE
Private-Message-System broken?

### ISSUE THREAD

**Issue by blackcrack** [PHP-Outburst/myUPB#13]
Klicking on the Private Message and become :

Fatal error: Call to undefined function getUsersPMBlockedList() in /homepages/30/d141495363/htdocs/myupb/forum/viewpm.php on line 75

and read old messages : 
Fatal error: Call to undefined function user_date() in /homepages/30/d141495363/htdocs/myupb/forum/viewpm.php on line 108

best regards
Blacky

**Comment by halamix2** [comment]
Fixed in #45
