### ISSUE TITLE
Prepare repository

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#19]
Add Phing with:
- [x] PHPDoc
- [x] PHPUnit
- [x] ContionusPHP

and autoloading (that's hard)
And this issue is made also to test how milestones on GitHub works

**Comment by blackcrack** [comment]
_thumps up_ ((in own thing)btw. 12h shift it's heavy if someone fresh in the job of S&S Guarding...)

**Comment by halamix2** [comment]
After 8 commits we have working CI :+1:
