### ISSUE TITLE
View Private Message

### ISSUE THREAD

**Issue by phpcodex** [PHP-Outburst/myUPB#42]
I was registered as Admin and created a new user "demo" - during this, I then sent demo a PM and had logged out then logged in as demo.

While logged in as demo, I went to read my PM and then received a blank page with the following:

`Fatal error: Uncaught Error: Call to undefined function getUsersPMBlockedList() in C:\xampp\htdocs\myUPB\viewpm.php:75 Stack trace: #0 {main} thrown in C:\xampp\htdocs\myUPB\viewpm.php on line 75`

**Comment by halamix2** [comment]
Connected to #39 somehow

**Comment by phpcodex** [comment]
Okay, so thank's to halamix showing me the -s in git log, he found what's happened. The Private Messages functions have moved to their own unique class. So I'm currently now just going to reference the class functions.
