### ISSUE TITLE
Automatic daylight saving time

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#43]
http://www.basildon.com/upb/viewtopic.php?id=6&t_id=10

Currently both forum and user timezone needs to be updated manually twice in a year instead of making it an automatic process.

**Comment by phpcodex** [comment]
How would you consider making it an automatic process?

**Comment by halamix2** [comment]
Maybe a checkbox "automatic daylight saving" which adds one hour to all displayed dates when checked would be enough?

**Comment by phpcodex** [comment]
I wasn't thinking of it being a user-interface, I mean, once they select their timezone, we should already perform the required +1 or -1 at the required intervals, but what is the intention?

I mean, what if the server is set to do this? PHP reads the server time, so if the server was connected to a NTP server, this issue would already be fixed, although granted in most cases this is false, except on windows platforms where it always is true.

So when we look at this, we should look at it from a view of A) The server doesn't automatically update (So we have the issue which needs fixing) and B) The server does automatically update, so actually, there is no issue.

**Comment by halamix2** [comment]
in some countries there is no daylight saving time so servers in those countries won't automatically update but the users can be from all over the world
