### ISSUE TITLE
Deprecated Youtube embedded code

### ISSUE THREAD

**Issue by sarnobat** [PHP-Outburst/myUPB#54]
### What happened

Youtube embedding in posts doesn't work as per Youtube's 2017 markup format (it uses an iframe instead of an object tag).

### Expected result

The video should display a thumbnail and be playable.

### How to reproduce

Create a new reply
Click the Youtube icon
Specify a URL such as https://www.youtube.com/watch?v=D4JEDOUPXbw

### Additional info

Just want to say thank you for resurrecting this project, I would take it over a SQL database forum anyday after almost 2 decades of bad experiences losing valuable forum data. Please continue to stick to your Unix Philosophy.

**Comment by halamix2** [comment]
For me it works in Firefox but the JS console indeed say about deprecated player

Currently if you want to play a video you have to input only D4JEDOUPXbw part, we should add full URL handling
